p1d <- read.table("household_power_consumption.txt", header=TRUE, na.strings = "?", sep =";")
p1d$Date <- as.Date(p1d$Date, "%d/%m/%Y")
d1 <- as.Date("2007-02-01")
d2 <- as.Date("2007-02-02")
p1d <- p1d[p1d$Date %in% d1:d2,]
p1d$newdate <- paste(p1d$Date, p1d$Time)
p1d$newdate <- as.POSIXct(p1d$newdate)
png("plot2.png", height = 480, width = 480)
plot(p1d$newdate, p1d$Global_active_power, type = 'l', ylab = "Global Active Power (kilowatts)", xlab = "")
dev.off()
